"""new fields in user model

Revision ID: 120860b3d904
Revises: b855ab34a097
Create Date: 2020-09-29 23:28:03.503306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120860b3d904'
down_revision = 'b855ab34a097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
