"""add language to posts

Revision ID: 392c44d36aa6
Revises: 8b47bfb388ad
Create Date: 2020-11-16 00:01:20.437948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392c44d36aa6'
down_revision = '8b47bfb388ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
